<template>
  <div>
    <div class="title">
      <h2>客家音樂篇</h2>
    </div>
    <hr />
    <p class="firstRow"></p>

    <h3>一、客家傳統歌謠</h3>
    <table rules="all" border="1" style="border: 1px solid" cellpadding="5">
      <thead>
        <tr>
          <th style="width: 20%">名稱</th>
          <th style="width: 20%">負責人</th>
          <th style="width: 25%">地址/電話</th>
          <th>其他聯絡方式</th>
          <th style="width: 25%">備註</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <p>臺北市中原客家崇正會祟正歌謠班</p>
          </td>
          <td>
            <p>班長</p>
            <p>許瑞</p>
          </td>
          <td>
            <p>臺北市大安區信義路三段157巷11號4樓教室（臺北市客家文化會館）</p>
            <p>02-8788-4541</p>
            <p>0921-831-786</p>
          </td>
          <td>
            <a target="_" href="https://blog.xuite.net/ho2104/blog">連結</a>
          </td>
          <td>
            <p>團練時間：每週一19:00-21:00</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>臺北市客家自強會樟新客家歌謠班</p>
          </td>
          <td>
            <p>戴紅櫻</p>
          </td>
          <td>
            <p>臺北市文山區一壽街22號9樓（樟新活動中心）</p>
            <p>02-2936-7260</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>臺北市客家長青會客家歌謠班</p>
          </td>
          <td>
            <p>理事</p>
            <p>劉金霖</p>
          </td>
          <td>
            <p>臺北市大安區和平東路二段95號之1</p>
            <p>02-2708-5995</p>
          </td>
          <td>
            <a target="_" href="https://ssl.thcp.org.tw/connections/clubs?page=3">連結</a>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>臺北客家鄉音合唱團</p>
          </td>
          <td>
            <p>陳采玲</p>
          </td>
          <td>
            <p>臺北市萬華區國興路1巷4號9樓之4</p>
            <p>臺北市客家文化會館（團練地點）</p>
            <p>02-2980-8613</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/pg/TPHKC/">連結</a>
          </td>
          <td>
            <p>成立於2016年</p>
            <p>團練時間：每週日14:00-17:00</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>台灣客家山歌團</p>
          </td>
          <td>
            <p>姜雲玉</p>
          </td>
          <td>
            <p>臺北市大安區信義路三段157巷11號（客家文化會館地下室）</p>
            <p>02-2771-0794</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/twhakka1991/">連結</a>
          </td>
          <td>
            <p>成立於1991年</p>
            <p>團練時間：每週一19:30-21:30</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>全球客家聲韻歌劇團</p>
          </td>
          <td>
            <p>張堂珍</p>
          </td>
          <td>
            <p>臺北市北投區明德路174巷8號2樓（臺北市客家文化主題公園）</p>
            <p>0933-056-319</p>
          </td>
          <td>
            <a href="mailto:lifechang8@gmail.com">連結</a>
          </td>
          <td>
            <p>團練時間：每週三14:00-17:00</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>忠勤客家歌謠班</p>
          </td>
          <td>
            <p>彭維熙</p>
          </td>
          <td>
            <p>臺北市中正區中華路二段293號B1樓（忠勤活動中心）</p>
            <p>0937-920-246</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>忠義客家歌謠班</p>
          </td>
          <td>
            <p>李榮堂</p>
          </td>
          <td>
            <p>臺北市中正區中華路二段315巷4弄1號（國盛活動中心）</p>
            <p>02-2307-2265</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>團練時間：每週三19:30-21:30</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>景美客家歌謠班</p>
          </td>
          <td>
            <p>陳錦月</p>
          </td>
          <td>
            <p>臺北市文山區羅斯福路六段393號7樓（景行活動中心）</p>
            <p>02-2937-5272</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>成立於2005年</p>
            <p>上課時間：每週四14:30-16:30</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>臺北市北區客家會石牌客家歌謠班</p>
          </td>
          <td>
            <p>班長</p>
            <p>羅方蓉</p>
          </td>
          <td>
            <p>臺北市士林區大東路75號2樓</p>
            <p>0936-060-607</p>
            <p>02-2821-9075</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>成立於1996年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>臺北市新竹縣同鄉會三興客家歌謠班</p>
          </td>
          <td>
            <p>林桂英</p>
          </td>
          <td>
            <p>臺北市信義區基隆路二段99號（三興國小視聽教室）</p>
            <p>0937-934-932</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/pg/Sanxingballadsclasses/">連結</a>
          </td>
          <td>
            <p>成立於1990年</p>
            <p>團練時間：每週五19:30-21:30</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>關渡客家歌謠班</p>
          </td>
          <td>
            <p>黃順平</p>
          </td>
          <td>
            <p>臺北市北投區知行路277號2樓</p>
            <p>02-2809-9036</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>新北市客家美聲發展協會</p>
          </td>
          <td>
            <p>梁文剛</p>
          </td>
          <td>
            <p>新北市板橋區市民大道三段247巷7號3樓</p>
            <p>02-2929-4679</p>
          </td>
          <td>
            <a target="_" href="https://www.hakka-associations.ntpc.gov.tw/files/15-1002-1671,c121-1.php">連結</a>
          </td>
          <td>
            <p>成立於2003年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>桃園市芙韻合唱協會</p>
          </td>
          <td>
            <p>指導</p>
            <p>游立佳</p>
          </td>
          <td>
            <p>桃園市龍潭區上林里溝東120之1號（桃園市龍潭區龍潭老人會館）</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/pg/hibiscusdiva/">連結</a>
          </td>
          <td>
            <p>成立於2010年</p>
            <p>團練時間：每週五14:00-16:00</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>桃園市客家文化歌謠協會</p>
          </td>
          <td>
            <p>理事</p>
            <p>陳秀珠</p>
          </td>
          <td>
            <p>桃園市平鎮區義興里義民路214號2樓</p>
            <p>桃園市平鎮區義興里集會所（團練地點）</p>
            <p>03-494-9243</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>成立於2007年</p>
            <p>團練時間：每週四19:00-21:00</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>桃園縣客家民謠研究學會</p>
          </td>
          <td>
            <p>黃金通</p>
          </td>
          <td>
            <p>桃園市中壢區元化路165巷17號9樓</p>
            <p>03-426-5648</p>
            <p>0933-110-163&nbsp;</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>成立於2003年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>碧霞鄉土客家民謠劇團</p>
          </td>
          <td>
            <p>趙彩雲</p>
          </td>
          <td>
            <p>桃園市中壢區三光路158巷12號</p>
            <p>桃園市平鎮區義民廟（團練地點）</p>
            <p>03-492-0676</p>
            <p>0912-671-732&nbsp;</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/LBCCTY/">連結</a>
          </td>
          <td>
            <p>成立於2015年</p>
            <p>團練時間：每週三14:00-16:00</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>財團法人新竹縣基督教客家福音協會</p>
          </td>
          <td>
            <p>白美月</p>
          </td>
          <td>
            <p>新竹縣竹東鎮自強路58號1樓&nbsp;</p>
            <p>03-594-5546</p>
          </td>
          <td>
            <a href="mailto:twhakka.chea@gmail.com">連結</a>
          </td>
          <td>
            <p>成立於1978年</p>
            <p>團練時間：每個月練習一次，於週二或四，依演出需求而定。</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>苗栗市玉華社區發展協會</p>
          </td>
          <td>
            <p>理事長</p>
            <p>張盛業</p>
          </td>
          <td>
            <p>苗栗縣苗栗市玉華里勵志街30巷1號</p>
            <p>0988-298-366</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/苗栗縣苗栗市玉華社區發展協會-1100749213285076/">連結</a>
          </td>
          <td>
            <p>成立於1985年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>苗栗市嘉盛社區發展協會</p>
          </td>
          <td>
            <p>總幹事</p>
            <p>張永昌</p>
          </td>
          <td>
            <p>苗栗縣苗栗市嘉盛里嘉盛街187號（嘉盛里社區發展中心）</p>
            <p>03-726-0309</p>
            <p>0932-666-120</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/jiasheng037260309/">連結</a>
          </td>
          <td>
            <p>成立於2012年</p>
            <p>團練時間：每週五19:00-21:00</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>苗栗縣大湖歌舞發展協會</p>
          </td>
          <td>
            <p>甘必成 張雲霞</p>
          </td>
          <td>
            <p>苗栗縣大湖鄉大湖村博愛路15號</p>
            <p>大湖鄉公所老人文康中心3樓（團練地點）</p>
            <p>03-799-1750</p>
            <p>0912-675-665</p>
          </td>
          <td>
            <a href="mailto:gan@taian.gov.com.tw">連結</a>
          </td>
          <td>
            <p>成立於2005年</p>
            <p>上課時間：每週二、五19:00-22:00</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>苗栗縣山城客家弦歌協會</p>
          </td>
          <td>
            <p>邱榮貴</p>
          </td>
          <td>
            <p>苗栗縣苗栗市維祥里維勝街62巷21弄12號</p>
            <p>苗栗火車站市場2樓（團練地點）</p>
            <p>0920-600-046</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/pg/Miaoli.hakka.association/">連結</a>
          </td>
          <td>
            <p>成立於2007年</p>
            <p>團練時間：每週四14:00-16:30</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>苗栗縣苗栗市維祥社區發展協會</p>
          </td>
          <td>
            <p>理事</p>
            <p>謝國章</p>
          </td>
          <td>
            <p>苗栗縣苗栗市維祥里光華街97號</p>
            <p>03-735-8435</p>
            <p>0932-565-111</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>南投縣埔里鎮客家文化發展協會</p>
          </td>
          <td>
            <p>曾子肅</p>
          </td>
          <td>
            <p>南投縣埔里鎮枇杷里樹人三街52號</p>
            <p>埔里鎮仁愛公園老人會館（團練地點）</p>
            <p>04-9299-1799</p>
            <p>0928-954-675</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/南投縣埔里鎮客家文化發展協會-Puli-Hakka-新版-1681221068828030/">連結</a>
          </td>
          <td>
            <p>成立於2005年</p>
            <p>團練時間：每週四14:30-16:30</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>府城哈客合唱團</p>
          </td>
          <td>
            <p>謝佩芬</p>
          </td>
          <td>
            <p>臺南市東區崇明二十二街58號</p>
            <p>臺南客家文化會館（團練地點）</p>
            <p>0933-710-946</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>成立於2004年</p>
            <p>團練時間：每週四14:30-16:30</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>臺南市南瀛客家文化協會歌謠班</p>
          </td>
          <td>
            <p>謝錦梅</p>
          </td>
          <td>
            <p>臺南市新營區民權路96之27號</p>
            <p>南瀛客家文化會館（團練地點）</p>
            <p>06-633-7627</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/pg/台南市南瀛客家文化協會-116898431697699/posts/">連結</a>
          </td>
          <td>
            <p>成立於2010年</p>
            <p>團練時間：每週四19:00-21:00</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>臺南市緣圓園客家樂舞團</p>
          </td>
          <td>
            <p>林宏峯</p>
          </td>
          <td>
            <p>臺南市南區新孝路102巷43號</p>
            <p>南瀛客家文化會館（團練地點）</p>
            <p>0912-174-290</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/台南市緣圓園客家樂舞團-241733949632351/">連結</a>
          </td>
          <td>
            <p>成立於2017年</p>
            <p>團練時間：每週三09:00-11:00</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>欣采樂綜藝團</p>
          </td>
          <td>
            <p>張素珠</p>
          </td>
          <td>
            <p>高雄市苓雅區四維四路186號</p>
            <p>高雄市博愛一路319號9樓（團練地點）</p>
            <p>07-322-6677</p>
          </td>
          <td>
            <a href="mailto:swiftlet@swiftlet.com.tw">連結</a>
          </td>
          <td>
            <p>成立於2006年</p>
            <p>團練時間：每週四19:30-21:30</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>美濃客家混聲合唱團</p>
          </td>
          <td>
            <p>藍勝生</p>
          </td>
          <td>
            <p>高雄市美濃區自強街一段391巷6號</p>
            <p>0933-661-823</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/高雄市美濃混聲合唱團-491930940887705/">連結</a>
          </td>
          <td>
            <p>成立於2005年</p>
            <p>團練時間：每週四19:00-21:00</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>美濃婦女合唱團</p>
          </td>
          <td>
            <p>團長</p>
            <p>李雪光</p>
            <p>行政總監</p>
            <p>劉蘭英</p>
          </td>
          <td>
            <p>高雄市美濃區雙峰街18號</p>
            <p>07-681-2179</p>
            <p>0911-880-179</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/hklee0321/">連結</a>
          </td>
          <td>
            <p>成立於1990年</p>
            <p>團練時間：每週三08:30-11:30</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>樂線綜藝團</p>
          </td>
          <td>
            <p>鍾鳳英</p>
          </td>
          <td>
            <p>高雄市三民區建工路433巷27號3樓</p>
            <p>寶珠溝活動中心4樓（團練地點）</p>
            <p>07-386-5208</p>
            <p>0929-416-817</p>
          </td>
          <td>
            <p></p>
          </td>
          <td>
            <p>成立於2006年</p>
            <p>團練時間：每週二19:30-21:30</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>屏東客家樂舞團</p>
          </td>
          <td>
            <p>林瑞輝</p>
          </td>
          <td>
            <p>屏東縣萬巒鄉褒忠路183號</p>
            <p>08-781-2456</p>
            <p>0929-355-368</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/PTHakka/">連結</a>
          </td>
          <td>
            <p>成立於2002年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>屏東縣竹田鄉客家樂舞協會</p>
          </td>
          <td>
            <p>劉秋琴</p>
          </td>
          <td>
            <p>屏東縣竹田鄉竹南村潮州路42號</p>
            <p>0983-508-779</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>屏東縣長治鄉客家民謠協會</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>屏東縣長治鄉潭頭村合興路124號</p>
            <p>08-721-7930</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>成立於1996年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>屏東縣高樹鄉客家樂舞協會</p>
          </td>
          <td>
            <p>張永雄</p>
          </td>
          <td>
            <p>屏東縣高樹鄉長榮村南昌路2之2號</p>
            <p>08-796-2136</p>
            <p>0963-200-267</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>藍衫樂舞團</p>
          </td>
          <td>
            <p>鍾芳廉</p>
          </td>
          <td>
            <p>屏東縣萬巒鄉萬和村南進路54號</p>
            <p>屏東縣麟洛鄉麟趾村仁愛街39號（團練地點）</p>
            <p>08-779-2055</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/藍衫樂舞團-Blue-Shirts-Music-and-Dance-Troupe-185867531445580/">連結</a>
          </td>
          <td>
            <p>成立於1993年</p>
            <p>團練時間：每週五20:00-22:00</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>花蓮客家合唱團</p>
          </td>
          <td>
            <p>李惠敏</p>
          </td>
          <td>
            <p>花蓮縣吉安鄉自立路9號</p>
            <p>0933-997-800</p>
          </td>
          <td>
            <a target="_" href="https://reurl.cc/QpQd0M">連結</a>
          </td>
          <td>&nbsp;</td>
        </tr>
      </tbody>
    </table>
    <br />
    <h3>二、客家傳統器樂（八音、北管、國樂）</h3>
    <table rules="all" border="1" style="border: 1px solid" cellpadding="5">
      <thead>
        <tr>
          <th style="width: 20%">名稱</th>
          <th style="width: 20%">負責人</th>
          <th style="width: 25%">地址/電話</th>
          <th>其他聯絡方式</th>
          <th style="width: 25%">備註</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <p>鄉音國樂團</p>
          </td>
          <td>
            <p>許瑞</p>
          </td>
          <td>
            <p>臺北市大安區信義路三段157巷11號4樓</p>
            <p>0921-831-786</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/hakkamelody/">連結</a>
          </td>
          <td>
            <p>成立於2001年</p>
            <p>團練時間：每週二18:30</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>榮芳客家北管國樂團</p>
          </td>
          <td>
            <p>陳石榮</p>
          </td>
          <td>
            <p>新北市樹林區太平路89號</p>
            <p>02-2681-8559</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>成立於2004年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>大華國樂文創團</p>
          </td>
          <td>
            <p>陳國芳</p>
          </td>
          <td>
            <p>桃園市八德區介壽路二段1022巷14號</p>
            <p>03-365-4568</p>
            <p>0935-025-143</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/大華國樂文創團陳國芳-1563159900469333/">連結</a>
          </td>
          <td>
            <p>成立於2000年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>和成八音團</p>
          </td>
          <td>
            <p>袁久琪</p>
          </td>
          <td>
            <p>桃園市八德區霄裡里官路缺78號</p>
            <p>0910-150-749</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/Hcg2232/">連結</a>
          </td>
          <td>
            <p>成立於1979年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>田屋北管八音團</p>
          </td>
          <td>
            <p>田文光</p>
          </td>
          <td>
            <p>新竹縣竹北市民生街11巷7號</p>
            <p>03-551-3320</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/TienWuBeiGuanBaYin/">連結</a>
          </td>
          <td>
            <p>成立於1989年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>新竹北埔八音團</p>
          </td>
          <td>
            <p>彭峻暘</p>
          </td>
          <td>
            <p>新竹縣北埔鄉南興村南興街63號</p>
            <p>0907-945-638</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/BeipuHakkaBayinGroup/">連結</a>
          </td>
          <td>
            <p>成立於2019年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>深井新興軒北管八音團</p>
          </td>
          <td>
            <p>江宥憲</p>
          </td>
          <td>
            <p>0932-113-836</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/新竹縣深井新興軒北管八音團-436454469857076/">連結</a>
          </td>
          <td>
            <p>「新興軒」成立於1983年，2014年改名為「深井新興軒北管八音團」。</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>關西祖傳隴西八音團</p>
          </td>
          <td>
            <p>彭金春</p>
            <p>彭宏男</p>
          </td>
          <td>
            <p>新竹縣關西鎮</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>苗栗陳家班北管八音團</p>
          </td>
          <td>
            <p>鄭榮興</p>
          </td>
          <td>
            <p>苗栗縣後龍鎮豐富里新東路 47之1號</p>
            <p>03-772-5099</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/MiaoliChenFamilyPaYinTroupe/">連結</a>
          </td>
          <td>
            <p>成立於1983年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>府城真樂軒八音樂團</p>
          </td>
          <td>
            <p>溫紹炳</p>
          </td>
          <td>
            <p>臺南市安平區文平路187巷113號</p>
            <p>0929-281-694</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>成立於2005年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>南方優客八音樂團</p>
          </td>
          <td>
            <p>劉育玲</p>
          </td>
          <td>
            <p>臺南市安平區文平路187巷113號</p>
            <p>0937-613-610</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>成立於2016年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>竹頭背客家八音團</p>
          </td>
          <td>
            <p>鍾兆生</p>
          </td>
          <td>
            <p>高雄市美濃區廣興街121號</p>
            <p>07-681-2538</p>
          </td>
          <td>
            <a target="_" href="https://reurl.cc/3jk3o0">連結</a>
          </td>
          <td>
            <p>成立於2012年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>美濃福安國小八音班</p>
          </td>
          <td>
            <p>謝宜文</p>
          </td>
          <td>
            <p>高雄市美濃區中山路二段358號（福安國小）</p>
            <p>0932-837-873</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>成立於2006年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>美濃國中八音社</p>
          </td>
          <td>
            <p>指導老師</p>
            <p>林作長</p>
          </td>
          <td>
            <p>高雄市美濃區中正路一段191號</p>
            <p>07-681-6166</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>成立於2006年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>美濃客家八音團</p>
          </td>
          <td>
            <p>鍾彩祥</p>
          </td>
          <td>
            <p>高雄市美濃區泰中路259巷23號</p>
            <p>07-682-2348</p>
            <p>0927-583-650</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>成立於2006年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>美濃客家八音班</p>
          </td>
          <td>
            <p>謝宜文</p>
          </td>
          <td>
            <p>高雄市美濃區</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>成立於2008年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>陳美子客家八音團</p>
          </td>
          <td>
            <p>陳美貴</p>
          </td>
          <td>
            <p>高雄市美濃區</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>陸豐客家八音劇團</p>
          </td>
          <td>
            <p>團長</p>
            <p>鄭淑敏</p>
          </td>
          <td>
            <p>高雄市鳳山區五甲一路208巷10號</p>
            <p>0981-991-880</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>成立於2003年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>大夥房藝術團</p>
          </td>
          <td>
            <p>團長</p>
            <p>劉國政</p>
            <p>聯絡人</p>
            <p>徐淑芳</p>
          </td>
          <td>
            <p>屏東縣麟洛鄉新田村民族路234號</p>
            <p>08-723-1258</p>
            <p>0921-696-046</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/大夥房藝術團-1371254872966824/">連結</a>
          </td>
          <td>
            <p>成立於2002年</p>
            <p>團練時間：每週一、三、五15:00-21:00</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>屏東縣八音協會</p>
          </td>
          <td>
            <p>鍾聰明</p>
          </td>
          <td>
            <p>屏東縣佳冬鄉六根村佳和路122號</p>
            <p>08-866-2228</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>成立於1988年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>花蓮瑞穗漢聲文化樂團</p>
          </td>
          <td>
            <p>劉振君</p>
          </td>
          <td>
            <p>花蓮縣</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>成立於1997年</p>
          </td>
        </tr>
      </tbody>
    </table>
    <br />
    <h3>三、客家傳統戲曲與表演形式</h3>
    <table rules="all" border="1" style="border: 1px solid" cellpadding="5">
        <thead>
          <tr>
            <th style="width: 20%">名稱</th>
            <th style="width: 20%">負責人</th>
            <th style="width: 25%">地址/電話</th>
            <th>其他聯絡方式</th>
            <th style="width: 25%">備註</th>
          </tr>
        </thead>
      <tbody>
        <tr>
          <td>
            <p>國立臺灣戲曲學院客家戲學系</p>
          </td>
          <td>
            <p>劉麗株</p>
          </td>
          <td>
            <p>臺北市文山區木柵路三段66巷8之1號</p>
            <p>02-2936-7231＃2551</p>
          </td>
          <td>
            <a target="_" href="https://rb017.tcpa.edu.tw">連結</a>
          </td>
          <td>
            <p>成立於2001年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>歡喜扮戲團</p>
          </td>
          <td>
            <p>林靜儀</p>
          </td>
          <td>
            <p>臺北市士林區德行西路97號2樓</p>
            <p>02-8866-1116</p>
            <p>02-8866-1090</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/UhanShiiTheatre/">連結</a>
          </td>
          <td>
            <p>成立於1995年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>偶偶偶劇團</p>
          </td>
          <td>
            <p>孫成傑</p>
          </td>
          <td>
            <p>臺北市大安區和平東路二段96巷20弄5號</p>
            <p>02-2733-0179</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/ooopt/?ref=page_internal">連結</a>
          </td>
          <td>
            <p>成立於2000年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>壹貳參戲劇團</p>
          </td>
          <td>
            <p>張瑛玲</p>
          </td>
          <td>
            <p>新北市三重區三和路二段168巷7號3樓</p>
            <p>0922-904-559</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/123theatre.123theatre">連結</a>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>山宛然客家布袋戲團</p>
          </td>
          <td>
            <p>黃武山</p>
          </td>
          <td>
            <p>新北市板橋區縣民大道三段83號3樓</p>
            <p>0932-330-003</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/山宛然客家布袋戲團-193976375896/">連結</a>
          </td>
          <td>
            <p>成立於2002年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>戲偶子劇團</p>
          </td>
          <td>
            <p>邱豐榮</p>
          </td>
          <td>
            <p>新北市新店區達觀路38號2樓之6</p>
            <p>0975-386-935</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/戲偶子劇團-123978480950659/">連結</a>
          </td>
          <td>
            <p>成立於2003年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>景勝戲劇團</p>
          </td>
          <td>
            <p>江玉玲</p>
          </td>
          <td>
            <p>桃園市平鎮區大智街25號</p>
            <p>03-457-8931</p>
            <p>0935-129-811</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/景勝戲劇團-1657899551112033/">連結</a>
          </td>
          <td>
            <p>成立於2003年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>貴鳳歌劇團</p>
          </td>
          <td>
            <p>陳鳳祺</p>
          </td>
          <td>
            <p>桃園市龍潭區自由街51號</p>
            <p>0911-241-388</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/a241388/">連結</a>
          </td>
          <td>
            <p>成立於2002年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>新月娥歌劇團</p>
          </td>
          <td>
            <p>范姜新堯</p>
            <p>劉雅如</p>
          </td>
          <td>
            <p>桃園市平鎮區大智街15號</p>
            <p>03-458-0110</p>
            <p>0933-507-453</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/新月娥歌劇團-334133613587392/">連結</a>
          </td>
          <td>
            <p>成立於1961年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>德泰戲劇團</p>
          </td>
          <td>
            <p>李小平</p>
          </td>
          <td>
            <p>桃園市中壢區龍岡路三段243巷53弄36號</p>
            <p>0919-362-104</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/a034586287/">連結</a>
          </td>
          <td>
            <p>成立於1988年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>松興戲劇團</p>
          </td>
          <td>
            <p>林興松</p>
          </td>
          <td>
            <p>新竹縣北埔鄉中山路51號</p>
            <p>0916-333-293</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/song.xing.opera/">連結</a>
          </td>
          <td>
            <p>成立於2003年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>新永光歌劇團</p>
          </td>
          <td>
            <p>翁義富</p>
          </td>
          <td>
            <p>新竹縣竹北市十興里49號</p>
            <p>03-550-3707</p>
            <p>0922-721-880</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>成立於1962年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>新樂園戲劇團</p>
          </td>
          <td>
            <p>劉秀鳳</p>
          </td>
          <td>
            <p>新竹縣竹北市縣政三街19號</p>
            <p>03-555-6358</p>
            <p>0933-265-173</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/新樂園戲劇團-1462229977363054/">連結</a>
          </td>
          <td>
            <p>成立於2003年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>霓雲社客家三腳採茶戲團</p>
          </td>
          <td>
            <p>徐進堯</p>
          </td>
          <td>
            <p>新竹縣竹東鎮</p>
            <p>03-582-2665</p>
          </td>
          <td>
            <a href="mailto:Psz0952814938@yahoo.com.tw">連結</a>
          </td>
          <td>
            <p>成立於1999年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>金滿圓戲劇團</p>
          </td>
          <td>
            <p>管建仲</p>
          </td>
          <td>
            <p>苗栗縣苗栗市福星里16鄰華清街9號</p>
            <p>03-773-0263</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>苗栗縣客家曲藝推展協會</p>
          </td>
          <td>
            <p>謝其國</p>
          </td>
          <td>
            <p>苗栗縣頭屋鄉中山街5之1號</p>
            <p>0937-813-833</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>成立於2005年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>榮興客家採茶劇團</p>
          </td>
          <td>
            <p>鄭月景</p>
          </td>
          <td>
            <p>苗栗縣苗栗市恭敬里24號</p>
            <p>03-772-5099</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/pg/romshinghakka/">連結</a>
          </td>
          <td>
            <p>成立於1988年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>大襟客客家文化藝術協會</p>
          </td>
          <td>
            <p>賴仁政</p>
          </td>
          <td>
            <p>0937-871-632</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/TaiKimHak">連結</a>
          </td>
          <td>
            <p>成立於2005年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>廖千盛布袋戲團</p>
          </td>
          <td>
            <p>廖千盛</p>
          </td>
          <td>
            <p>雲林縣二崙鄉崙東村仁和路142巷27號</p>
            <p>05-598-8188</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>成立於 2013年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>廖千順布袋戲團</p>
          </td>
          <td>
            <p>廖千順</p>
          </td>
          <td>
            <p>雲林縣二崙鄉三和村三和路28之49號</p>
            <p>0933-509-888</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/廖千順布袋戲團-1842955999266025/">連結</a>
          </td>
          <td>
            <p>成立於2001年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>廖文和布袋戲團</p>
          </td>
          <td>
            <p>廖文和</p>
          </td>
          <td>
            <p>雲林縣二崙鄉紹興路19號</p>
            <p>05-598-3777</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/wen.holiao">連結</a>
          </td>
          <td>
            <p>成立於1976年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>走馬蓋文化藝術表演團</p>
          </td>
          <td>
            <p>楊秀春</p>
          </td>
          <td>
            <p>高雄市前鎮區崗山中街255號4樓之2</p>
            <p>0931-616-986</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>成立於2004年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>哈旗鼓文化藝術表演團</p>
          </td>
          <td>
            <p>楊秀春</p>
          </td>
          <td>
            <p>高雄市前鎮區崗山中街255號4樓之1</p>
            <p>0931-616-986</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/HaChiGu/">連結</a>
          </td>
          <td>
            <p>成立於2004年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>世客文化藝術團</p>
          </td>
          <td>
            <p>吳川鈴</p>
          </td>
          <td>
            <p>屏東縣屏東市豐田里水源巷12號</p>
            <p>08-732-3202</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/世客文化藝術團-336912869758607/">連結</a>
          </td>
          <td>
            <p>成立於2003年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>李文古歌劇團</p>
          </td>
          <td>
            <p>李盛發</p>
          </td>
          <td>
            <p>屏東縣內埔鄉內田村復興路38號</p>
            <p>0932-882-984</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/LiWenGuGeJuTuan/">連結</a>
          </td>
          <td>
            <p>成立於2003年</p>
          </td>
        </tr>
      </tbody>
    </table>
    <br />
  </div>
</template>
