<template>
  <div>
    <div class="title">
      <h2>南管音樂篇</h2>
    </div>
    <hr />
    <p class="firstRow"></p>
    <h3>一、南管團體</h3>
    <table rules="all" border="1" style="border: 1px solid" cellpadding="5">
      <tbody>
        <tr>
          <td rowspan="2">
            <p>名稱</p>
          </td>
          <td rowspan="2">
            <p>負責人</p>
          </td>
          <td rowspan="2">
            <p>地址/電話</p>
          </td>
          <td rowspan="2">
            <p>其他聯絡方式</p>
          </td>
          <td colspan="3">
            <p>備註</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>立案情形</p>
          </td>
          <td>
            <p>成立時間</p>
          </td>
          <td>
            <p>活動概況</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>基隆市閩南第一樂團</p>
          </td>
          <td>
            <p>呂光輝</p>
          </td>
          <td>
            <p>基隆市孝西路10號之2（陸橋下）</p>
            <p>02-2424-1308</p>
            <p>0937-880-367</p>
          </td>
          <td>
            <p>https://www.facebook.com/groups/217228464957550/</p>
          </td>
          <td>
            <p>已立案</p>
          </td>
          <td>
            <p>日治時期</p>
          </td>
          <td>
            <p>每週二晚上、週六下午練習</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>中華絃管研究團</p>
          </td>
          <td>
            <p>莊國章</p>
          </td>
          <td>
            <p>臺北市南港區市民大道七段355巷8號1樓（山韻樂器行）</p>
            <p>02-2577-5518</p>
          </td>
          <td>
            <p>https://www.facebook.com/中華絃管研究團-328596864328765/</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：2004換發登記證</p>
          </td>
          <td>
            <p>1984</p>
          </td>
          <td>
            <p>
              每週三下午資深館員拍館，每週三晚上學員練習，每週日下午共同團練
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>臺北市和鳴南樂社團</p>
          </td>
          <td>
            <p>魏秀蓉</p>
          </td>
          <td>
            <p>臺北市大同區南京西路344巷2號M樓（臺北法主公廟）</p>
            <p>02-2556-2964</p>
          </td>
          <td>
            <p>
              https://www.facebook.com/和鳴南樂社-He-Ming-Nanguan-Ensemble-南管館閣-175327956220495/
            </p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：2007</p>
          </td>
          <td>
            <p>1997</p>
          </td>
          <td>
            <p>上課時間：每週一、四18:00-21:00</p>
            <p>拍館時間：每週五晚上</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>台北市閩南樂府管絃研究會</p>
          </td>
          <td>
            <p>負責人</p>
            <p>呂進發</p>
            <p>總幹事</p>
            <p>呂瑞華</p>
          </td>
          <td>
            <p>臺北市大同區延平北路三段61巷32號2樓</p>
            <p>02-2591-1302</p>
          </td>
          <td>
            <p>
              https://www.facebook.com/台北市閩南樂府弦管研究會-2196238770415810/
            </p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：1962</p>
          </td>
          <td>
            <p>1961</p>
          </td>
          <td>
            <p>簡稱閩南樂府，拍館時間：每週六晚上</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>臺北市華聲南樂團</p>
          </td>
          <td>
            <p>負責人</p>
            <p>蕭志恆</p>
            <p>團長</p>
            <p>鄭靜芬</p>
          </td>
          <td>
            <p>臺北市大同區延平北路一段22號6樓之2（登記地址）</p>
            <p>02-29217605</p>
            <p>臺北市大同區承德路三段54號4樓（通訊地址）</p>
          </td>
          <td>
            <p>https://www.facebook.com/HuaSiengNanGuan/</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：2008</p>
          </td>
          <td>
            <p>1985</p>
          </td>
          <td>
            <p>
              簡稱華聲社，指導老師：林珀姬、蕭志恆、徐智城、盧盈妤。每週一初級班19:00-21:00、每週日進階班14:00-17:00、每週三高階班19:00-21:00
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>心心南管樂坊</p>
          </td>
          <td>
            <p>王心心</p>
          </td>
          <td>
            <p>臺北市大同區興城街10巷16號1樓</p>
            <p>02-2557-8239</p>
            <p>02-2557-8907（傳真）</p>
          </td>
          <td>
            <p>https://www.facebook.com/NanguanXinXin/</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：2007</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>每週四</p>
            <p>19:00-22:00練習</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>江之翠劇場</p>
          </td>
          <td>
            <p>魏美慧</p>
          </td>
          <td>
            <p>臺北市北投區大度路三段301巷28弄16號2樓（團址）</p>
            <p>臺北市大同區迪化街一段21號大稻埕戲苑7樓排練教室（排練）</p>
          </td>
          <td>
            <p>https://www.facebook.com/gangatsui</p>
            <p>gangatsui@gmail.com</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：2017</p>
          </td>
          <td>
            <p>1993</p>
          </td>
          <td>
            <p>
              原於新北市立案，2017年11月於臺北市重新立案登記。團練時間：每週六18:00-21:00、每週日9:30-12:30
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>青和南管</p>
          </td>
          <td>
            <p>魏伯年</p>
          </td>
          <td>
            <p>無固定地址</p>
          </td>
          <td>
            <p>https://www.facebook.com/qhnanguan/</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>2015</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>南樂貞遠社</p>
          </td>
          <td>
            <p>負責人</p>
            <p>傅貞儀</p>
            <p>社長</p>
            <p>丁崧耀</p>
          </td>
          <td>
            <p>臺北市萬華區大埔街8號4樓（館址）</p>
          </td>
          <td>
            <p>
              <a href="https://www.facebook.com/南樂貞遠社-101867654679195"
                >https://www.facebook.com/南樂貞遠社-101867654679195</a
              >
            </p>
            <p>zx456806@gmail.com</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：2019</p>
          </td>
          <td>
            <p>2019</p>
          </td>
          <td>
            <p>
              上課時間：每週六14:00-17:00、每週日13:00-17:00、每週一19:00-21:00，指導老師傅貞儀
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>詠吟樂坊</p>
          </td>
          <td>
            <p>何欽龍</p>
          </td>
          <td>
            <p>臺北市松山區撫遠街380巷14號4樓</p>
            <p>02-2766-2603</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>
            <p>2004</p>
          </td>
          <td>
            <p>團長何欽龍、教師林珀姬</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>福壽宮南樂團</p>
          </td>
          <td>
            <p>陳銘富</p>
          </td>
          <td>
            <p>臺北市大同區敦煌路2-1號（大龍峒福壽宮）</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>漢唐樂府南管古典樂舞團</p>
          </td>
          <td>
            <p>陳美娥</p>
          </td>
          <td>
            <p>宜蘭縣五結鄉五結路三段718號（聯絡地址）</p>
          </td>
          <td>
            <p>
              https://www.facebook.com/漢唐樂府-HanTang-YueFu-184122174945933/
            </p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：2004換發登記證</p>
          </td>
          <td>
            <p>1983</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>永和南樂社</p>
          </td>
          <td>
            <p>陳宗碑</p>
          </td>
          <td>
            <p>新北市永和區勵行街44號（團址）</p>
            <p>新北市永和區勵行街44號3樓（排練室）</p>
            <p>02-2921-2866</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>已立案</p>
            <p>立案時間：1995</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>每週一、三、五19:00-21:00</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>南薰閣</p>
          </td>
          <td>
            <p>徐智城</p>
          </td>
          <td>
            <p>新北市板橋區館前東路116號6樓之12（館址）</p>
            <p>板橋435藝文特區3110工作室（排練）</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>已立案</p>
            <p>立案時間：2015</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>每週五14:00-17:00練習</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>浯江南樂社</p>
          </td>
          <td>
            <p>李國俊</p>
          </td>
          <td>
            <p>新北市永和區中正路527號8樓之1</p>
            <p>02-2231-0006</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>已立案</p>
            <p>立案時間：1992</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>金門鄉親聚會，不定時拍館</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>中瀛南樂社</p>
          </td>
          <td>
            <p>社長</p>
            <p>李秀媚</p>
            <p>教師</p>
            <p>陳枝財</p>
          </td>
          <td>
            <p>臺中市太平區中和街457巷17號</p>
            <p>04-2277-8665</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>已立案</p>
            <p>立案時間：2004</p>
          </td>
          <td>
            <p>2004</p>
          </td>
          <td>
            <p>每週四19:00-21:00練習</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>合和藝苑</p>
          </td>
          <td>
            <p>團長</p>
            <p>李碧珍</p>
          </td>
          <td>
            <p>臺中市沙鹿區四平街123號</p>
            <p>04-26236796</p>
          </td>
          <td>
            <p>https://www.facebook.com/合和藝苑-579899192117301/</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：1993</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>
              南管音樂傳習：每週六19:00-21:30、南管戲排練：每週日19:00-21:30
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>長隆南樂社</p>
          </td>
          <td>
            <p>社長</p>
            <p>鄭慧鋒</p>
            <p>團長</p>
            <p>吳炳慧</p>
          </td>
          <td>
            <p>臺中市南區台中路182巷2號（聯絡地址）</p>
          </td>
          <td>
            <p>https://www.facebook.com/profile.php?id=100002456890010</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：2015</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>每週三下午練習</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>梨園樂坊南管樂團</p>
          </td>
          <td>
            <p>戴英宏</p>
          </td>
          <td>
            <p>臺中市霧峰區中正路762-1號1樓（團址）</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>已立案</p>
            <p>立案時間：2008</p>
          </td>
          <td>
            <p>1997</p>
          </td>
          <td>
            <p>
              創辦人陳焜晉過世後，2008由戴英宏承繼，每週四、五14:00-16:00練習
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>清雅樂府</p>
          </td>
          <td>
            <p>黃珠玲</p>
          </td>
          <td>
            <p>臺中市清水區鎮新路298巷11號（館址）</p>
            <p>臺中市清水區大街路206號（紫雲巖4樓）</p>
            <p>04-2623-2422</p>
          </td>
          <td>
            <p>https://www.facebook.com/Taichung.CHING.YA.YUEH.FU/</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：1996</p>
          </td>
          <td>
            <p>1953</p>
          </td>
          <td>
            <p>每週三、五20:00-22:00、每週六15:00-17:00練習</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>善德堂南樂社</p>
          </td>
          <td>
            <p>社長</p>
            <p>劉欽沂</p>
          </td>
          <td>
            <p>臺中市南屯區水碓巷1號04-04-2479-2217</p>
          </td>
          <td>
            <p>https://www.facebook.com/liuchini1103</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>2013</p>
          </td>
          <td>
            <p>教師馬一瑚、理事長陳光耀。練習時間：每週二、四19:00-21:30</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>龍天南樂府</p>
          </td>
          <td>
            <p>陳素玉</p>
          </td>
          <td>
            <p>臺中市龍井區竹坑里中華路一段219號（龍天宮）</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>
            <p>2010</p>
          </td>
          <td>
            <p>
              原由鄭洪員老師指導。2018年改由林吳素霞老師指導。每週一18:00-21:00上課
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>樂成宮南樂社</p>
          </td>
          <td>
            <p>周芳麗</p>
          </td>
          <td>
            <p>臺中市東區旱溪街48號（樂成宮）</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>
            <p>每週五19:00-21:00練習</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>鹿港永樂絃管</p>
          </td>
          <td>
            <p>林秋菊</p>
          </td>
          <td>
            <p>彰化縣鹿港鎮埔崙里永寧街132號</p>
            <p>04-775-6077</p>
          </td>
          <td>
            <p>
              https://www.facebook.com/鹿港永樂絃管南管樂團-104073238115940/
            </p>
            <p>ug61837361636@gmail.com</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：2005</p>
          </td>
          <td>
            <p>2005</p>
          </td>
          <td>
            <p>
              簡稱永樂絃管，每週日10:00-12:00借用彰化縣南北管音樂戲曲館教室練習
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>鹿港雅正齋南管樂團</p>
          </td>
          <td>
            <p>董建林</p>
          </td>
          <td>
            <p>彰化縣鹿港鎮忠孝路403號</p>
            <p>（老人會）</p>
            <p>04-777-5514</p>
          </td>
          <td>
            <p>https://www.facebook.com/groups/618296004968390/</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：1998</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>簡稱雅正齋，每週一、二、四19:30-21:30練習</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>鹿港遏雲齋南管樂團</p>
          </td>
          <td>
            <p>郭元湧</p>
          </td>
          <td>
            <p>彰化縣鹿港鎮八德路149 號（曲館）</p>
            <p>彰化縣鹿港鎮郭厝里郭厝巷147號</p>
            <p>04-778-5787</p>
            <p>04-777-5660</p>
          </td>
          <td>
            <p>https://www.facebook.com/鹿港遏雲齋南管樂團-180173595360938/</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：1997</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>簡稱遏雲齋，每週六、日09:30-11:30練習</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>鹿港聚英社南樂團</p>
          </td>
          <td>
            <p>許耀升</p>
          </td>
          <td>
            <p>彰化縣鹿港鎮金門街81號（龍山寺）</p>
            <p>04-726-3817</p>
            <p>04-778-6775</p>
            <p>04-781-1299</p>
          </td>
          <td>
            <p>https://www.facebook.com/LKnankuan/</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：1998</p>
          </td>
          <td>
            <p>1821</p>
          </td>
          <td>
            <p>簡稱聚英社，每週六、日10:00-12:00練習</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>彰化縣文化局南管實驗樂團</p>
          </td>
          <td>
            <p>教師</p>
            <p>林吳素霞</p>
          </td>
          <td>
            <p>彰化縣彰化市平和七街66號（南北管音樂戲曲館上課）</p>
            <p>04-751-0709</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>
            <p>每週日9:00-12:00上課</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>元長大漢閣</p>
          </td>
          <td>
            <p>吳德祥</p>
          </td>
          <td>
            <p>雲林縣元長鄉元北路32之20號（長北村集會所活動中心）</p>
          </td>
          <td>
            <p>https://www.facebook.com/大漢閣南管樂團-1843602999005949/</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>
            <p>每週一晚上練習</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>汾雅齋南管樂團</p>
          </td>
          <td>
            <p>蘇仁義</p>
          </td>
          <td>
            <p>雲林縣北港鎮公館路5 號</p>
          </td>
          <td>
            <p>https://www.facebook.com/nanguan.fen.ya/</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：2019 重新登記</p>
          </td>
          <td>
            <p>2011</p>
          </td>
          <td>
            <p>每週六19:30-21:30練習</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>笨港集斌社</p>
          </td>
          <td>
            <p>社長</p>
            <p>許澤猛</p>
            <p>執行團長</p>
            <p>黃崇榮</p>
          </td>
          <td>
            <p>雲林縣北港鎮華勝路130號（團址）</p>
            <p>雲林縣北港鎮文化路246號（日興堂老闆提供之練習場地）</p>
            <p>05-783-4085</p>
          </td>
          <td>
            <p>https://www.facebook.com/pg/集斌社-274917685886071/</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：2008</p>
          </td>
          <td>
            <p>1999</p>
          </td>
          <td>
            <p>基礎班：每週二18:30-21:30、團練：每週五18:30-21:30</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>鳳聲閣民俗樂團</p>
          </td>
          <td>
            <p>張淑媛</p>
          </td>
          <td>
            <p>嘉義市文雅街175巷7弄31號</p>
            <p>05-284-3576（沈怡秀團長）</p>
          </td>
          <td>
            <p>https://www.facebook.com/pg/鳳聲閣-559488677847210/</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：2005</p>
          </td>
          <td>
            <p>2005</p>
          </td>
          <td>
            <p>每週五18:00-21:00練習</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>臺南市南聲社</p>
          </td>
          <td>
            <p>林毓汀</p>
          </td>
          <td>
            <p>臺南市南區仁南街86號（南廠水門宮2樓）</p>
            <p>06-263-3929</p>
          </td>
          <td>
            <p>https://www.facebook.com/tainannanshan/</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：1980</p>
          </td>
          <td>
            <p>1915年（日大正四年）</p>
          </td>
          <td>
            <p>
              上課時間：每週三14:00-17:00、每週六15:00-18:00、練習時間：每週六晚上
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>安溪寮龍御社</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>臺南市後壁區長安里42號（安溪寮福安寺）</p>
            <p>06-636-1702</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>
            <p>每週五上午在福安寺土地公廟演練</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>海寮普陀寺清和社</p>
          </td>
          <td>
            <p>方阿婿</p>
          </td>
          <td>
            <p>臺南市安定區海寮110號（海寮普陀寺）</p>
          </td>
          <td>
            <p>https://www.facebook.com/海寮南樂清和社-1555814204633359/</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>1856</p>
          </td>
          <td>
            <p>每週四、五19:30-21:30練習。參與西港刈香</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>振聲社</p>
          </td>
          <td>
            <p>負責人：</p>
            <p>陳進丁</p>
            <p>社長：</p>
            <p>蔡芬得（2022）</p>
            <p>/郭雅君（2023）</p>
          </td>
          <td>
            <p>臺南市中西區忠孝街112號</p>
            <p>06-228-9473</p>
          </td>
          <td>
            <p>https://www.facebook.com/TNtsinsingsia/</p>
            <p>Instagram：臺南振聲社</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：2000</p>
          </td>
          <td>
            <p>1793年（清乾隆五十八年）</p>
          </td>
          <td>
            <p>每週五：19:30-22:00、每週六：14:00-22:00上課練習</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>喜樹國小南管社團喜聲社</p>
          </td>
          <td>
            <p>校長</p>
            <p>黃懷慧</p>
            <p>教師</p>
            <p>張栢仲</p>
          </td>
          <td>
            <p>臺南市南區喜樹路133號</p>
            <p>06-262-2462</p>
          </td>
          <td>
            <p>https://www.facebook.com/喜聲社-664447443654571/</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>
            <p>上課時間：每週三14:00-16:00、每週六08:30-10:30</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>灣裡慶安堂和聲社</p>
          </td>
          <td>
            <p>杜清蔭</p>
          </td>
          <td>
            <p>臺南市南區灣裡路282巷38號（慶安堂）</p>
            <p>06-262-0536</p>
          </td>
          <td>
            <p>https://www.facebook.com/Wanli.Lamim/</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>日治時期</p>
          </td>
          <td>
            <p>每週一、二、五20:00-22:00練習</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>內門南海紫竹寺新興庄集聲社南管</p>
          </td>
          <td>
            <p>余忠任</p>
          </td>
          <td>
            <p>高雄市內門區內豐里內埔82號（南海紫竹寺）</p>
            <p>07-667-1400</p>
          </td>
          <td>
            <p>https://www.facebook.com/profile.php?id=100064192566070</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>1976</p>
          </td>
          <td>
            <p>
              民國前成立於內門紫竹寺，1976年移至南海紫竹寺。每週六19:00-21:00練習。農曆初一、十五祀神
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>右昌光安南樂社</p>
          </td>
          <td>
            <p>洪進益</p>
          </td>
          <td>
            <p>高雄市楠梓區右昌一巷1號（右昌元帥府）</p>
            <p>07-361-6232（元帥府）</p>
            <p>07-361-7209（光安社）</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>
            <p>每週二、四、六20:00-22:00團練</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>茄萣金鑾宮振南社</p>
          </td>
          <td>
            <p>薛寶源</p>
          </td>
          <td>
            <p>高雄市茄萣區港東街111號（茄萣金鑾宮）</p>
          </td>
          <td>
            <p>https://www.facebook.com/groups/225183657584348/</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>
            <p>每週四、日19:00-22:00</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>茄萣賜福宮振樂社</p>
          </td>
          <td>
            <p>邱秋燕</p>
          </td>
          <td>
            <p>高雄市茄萣區賜福宮四館</p>
            <p>07-690-4226</p>
          </td>
          <td>
            <p>https://www.facebook.com/QiedingNanguan</p>
          </td>
          <td>
            <p>已立案</p>
          </td>
          <td>
            <p>1967</p>
          </td>
          <td>
            <p>每週一、三晚間練習</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>阿蓮薦善堂薦善南樂社</p>
          </td>
          <td>
            <p>陳三寶</p>
          </td>
          <td>
            <p>高雄市阿蓮區民族路206巷26號（阿蓮薦善堂）</p>
            <p>07-631-2058</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>崎漏正順廟正聲南樂社</p>
          </td>
          <td>
            <p>邱逸文</p>
          </td>
          <td>
            <p>高雄市茄萣區崎漏里崎漏路68號（崎漏正順廟）</p>
            <p>07-698-9982</p>
          </td>
          <td>
            <p>https://www.facebook.com/profile.php?id=100088399183146</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>1970</p>
          </td>
          <td>
            <p>
              2022年研習班於11月13日開班，每週日19:30-21:30上課，蔡芬得老師指導
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>廣益南樂社</p>
          </td>
          <td>
            <p>許丁春</p>
          </td>
          <td>
            <p>高雄市大社區中華路127號（大社青雲宮）</p>
            <p>07-351-4719</p>
          </td>
          <td>
            <p>https://www.facebook.com/GuangYiNanYue/</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：2019</p>
          </td>
          <td>
            <p>2006</p>
          </td>
          <td>
            <p>每週四19:30-21:30練習，並配合廟務出陣</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>臺東縣閩南音樂聚英社</p>
          </td>
          <td>
            <p>理事長</p>
            <p>黃金美</p>
          </td>
          <td>
            <p>臺東縣臺東市博愛路421號2樓</p>
          </td>
          <td>
            <p>https://www.facebook.com/groups/139815092737543/</p>
            <p>https://mypaper.pchome.com.tw/catzoo638</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：1977</p>
          </td>
          <td>
            <p>1947</p>
          </td>
          <td>
            <p>每週六下午活動</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>斗門南樂研習社</p>
          </td>
          <td>
            <p>陳朝清</p>
            <p>陳金潭</p>
          </td>
          <td>
            <p>金門縣金沙鎮斗門35之2號</p>
            <p>082-351-069</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>已立案</p>
            <p>立案時間：1999</p>
          </td>
          <td>
            <p>1964</p>
          </td>
          <td>
            <p>每週日19:00-21:00練習，出席人數約6人</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>仙洲薪傳南音社</p>
          </td>
          <td>
            <p>陳榮泰</p>
          </td>
          <td>
            <p>金門縣金沙鎮三山村碧山1號（館址）</p>
          </td>
          <td>
            <p>https://www.facebook.com/groups/200638373879957</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：2018</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>每週一、二、三、四、五晚上19:30-21:30</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>金沙絃管社</p>
          </td>
          <td>
            <p>張國強</p>
          </td>
          <td>
            <p>金門縣金沙鎮汶沙里信義路3-1號</p>
            <p>082-352-620</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>已立案</p>
            <p>立案時間：1994</p>
          </td>
          <td>
            <p>1941</p>
          </td>
          <td>
            <p>每週五19:30-21:30練習，出席人數約6人</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>金門南樂研究社</p>
          </td>
          <td>
            <p>李清海</p>
          </td>
          <td>
            <p>金門縣金城城隍廟內右廂房</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>已立案</p>
            <p>立案時間：1995</p>
          </td>
          <td>
            <p>1875年 （清光緒元年）</p>
          </td>
          <td>
            <p>練習時間：每週二19:30-21:30、每週日14:00-16:00</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>金門樂府傳統樂團</p>
          </td>
          <td>
            <p>團長</p>
            <p>楊明雪</p>
          </td>
          <td>
            <p>金門縣珠浦西路50巷2弄9號（通訊地址）</p>
            <p>金門縣金城鎮民族路261號（金城體育館看臺下教室，團練地址）</p>
          </td>
          <td>
            <p>https://www.facebook.com/groups/176691215689013/</p>
            <p>jyps@mail.com.edu.tw</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：1999</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>簡稱金門樂府，練習時間：每週二、三、四19:30-21:30</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>金門縣浯江南樂研習社</p>
          </td>
          <td>
            <p>理事長</p>
            <p>陳亞福</p>
          </td>
          <td>
            <p>金門縣金沙鎮成功路1號（館址）</p>
            <p>082-353-611</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>已立案</p>
            <p>立案時間：2008</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>每週三、六19:30-21:30練習</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>烈嶼群聲南樂社</p>
          </td>
          <td>
            <p>理事長</p>
            <p>李安心</p>
          </td>
          <td>
            <p>金門縣烈嶼鄉西路35號</p>
            <p>082-364-218</p>
          </td>
          <td>
            <p>https://www.facebook.com/groups/341640913150301/</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：2004</p>
          </td>
          <td>
            <p>2003</p>
          </td>
          <td>
            <p>練習時間：每日09:30-11:30</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>澎湖縣西瀛堂南管學會</p>
          </td>
          <td>
            <p>蘇菁萍</p>
          </td>
          <td>
            <p>澎湖縣馬公市中華路230號（澎湖縣文化局南管研習班）</p>
            <p>06-926-1141#4</p>
            <p>06-927-6602（傳真）</p>
          </td>
          <td>
            <p>geosu5438@yahoo.com.tw（蘇菁萍）</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：2004</p>
          </td>
          <td>
            <p>2004</p>
          </td>
          <td>
            <p>上課時間：每週一19:00-21:00、每週六15:00-17:00</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>南管新錦珠劇團</p>
          </td>
          <td>
            <p>梁陳錦珠</p>
          </td>
          <td>
            <p>新北市三重區成功路88號9樓</p>
          </td>
          <td>
            <p>https://www.facebook.com/Xinjinzhu.Troupe</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：2007</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>
              排練時間：每週六13:00-16:00、18:00-21:00、每週日09:00-12:00、14:00-19:00
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>錦成閣高甲團</p>
          </td>
          <td>
            <p>昌錦龍</p>
          </td>
          <td>
            <p>彰化縣埔鹽鄉西湖村大新路2巷63號</p>
            <p>04-865-9431</p>
          </td>
          <td>
            <p>https://www.facebook.com/groups/242022802590204/</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：2006</p>
          </td>
          <td>
            <p>1877年（清光緒三年）</p>
          </td>
          <td>&nbsp;</td>
        </tr>
      </tbody>
    </table>
    <p></p>
    <p>文武郎君、太平歌</p>
    <table rules="all" border="1" style="border: 1px solid" cellpadding="5">
      <tbody>
        <tr>
          <td rowspan="2">
            <p>名稱</p>
          </td>
          <td rowspan="2">
            <p>負責人</p>
          </td>
          <td rowspan="2">
            <p>地址/電話</p>
          </td>
          <td rowspan="2">
            <p>其他聯絡方式</p>
          </td>
          <td colspan="3">
            <p>備註</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>立案情形</p>
          </td>
          <td>
            <p>成立時間</p>
          </td>
          <td>
            <p>活動概況</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>三五甲文武郎君</p>
          </td>
          <td>
            <p>蔡政達</p>
          </td>
          <td>
            <p>臺南市佳里區鎮山街85巷91號</p>
          </td>
          <td>
            <p>https://www.facebook.com/bunbulongkun/</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>約於1836年至1847年間（道光十六年至道光二十七年）成立</p>
          </td>
          <td>
            <p>參與西港刈香。每週日19:00-21:00練習</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>公親寮清水寺天子門生</p>
          </td>
          <td>
            <p>黃秋蘭</p>
          </td>
          <td>
            <p>臺南市安南區公學路一段228號（公親寮清水寺）</p>
            <p>06-255-2762</p>
          </td>
          <td>
            <p>https://www.facebook.com/pg/KTLTPK/</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>
            <p>參與西港刈香。有活動才團練</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>永吉吉安宮天子門生</p>
          </td>
          <td>
            <p>曾海燈</p>
          </td>
          <td>
            <p>臺南市七股區永吉里16-9號（永吉吉安宮）</p>
            <p>06-787-2024</p>
          </td>
          <td>
            <p>https://www.facebook.com/永吉吉安宮天子門生-306785639382578/</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>
            <p>參與西港刈香。週六晚上練習</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>麻豆巷口集英社太平清歌</p>
          </td>
          <td>
            <p>郭武驥</p>
          </td>
          <td>
            <p>臺南市麻豆區巷口里和平路3號（巷口慶安宮）</p>
            <p>06-571-8909</p>
            <p>臺南市麻豆區謝厝寮 44-15 號 06-572-1614</p>
          </td>
          <td>
            <p>https://www.facebook.com/pg/集英社太平清歌-579225785604662/</p>
          </td>
          <td>
            <p>已立案</p>
            <p>立案時間：2019</p>
          </td>
          <td>
            <p>1917</p>
          </td>
          <td>
            <p>每週一、三19:30-21:00練習</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>港墘港興宮天子門生</p>
          </td>
          <td>
            <p>黃正儀</p>
          </td>
          <td>
            <p>臺南市佳里區通興里港墘1之2號（港墘港興宮）</p>
            <p>06-787-3775</p>
          </td>
          <td>
            <p>
              https://www.facebook.com/港墘太平歌團天子門生陣-1749207195291500/
            </p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>
            <p>參與西港刈香。每週五19:30-21:00練習，黃玉惠老師指導</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>內門紫竹寺番仔路和樂軒太平歌陣</p>
          </td>
          <td>
            <p>鄭永辰</p>
          </td>
          <td>
            <p>高雄市內門區觀亭里番子路25之1號（番仔路神農宮）</p>
            <p>07-667-4427</p>
          </td>
          <td>
            <p>
              https://www.facebook.com/內門紫竹寺番仔路和樂軒太平歌-1677233442301092/
            </p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>
            <p>參與內門迎佛祖活動</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>茄萣金鑾宮太平歌樂社</p>
          </td>
          <td>
            <p>社長</p>
            <p>楊麗蓉</p>
            <p>總幹事</p>
            <p>薛美君</p>
          </td>
          <td>
            <p>高雄市茄萣區保定里港東街111號（茄萣金鑾宮）</p>
            <p>07-690-2948</p>
          </td>
          <td>
            <p>https://www.facebook.com/茄萣金鑾宮天子文生-476038909159612/</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>頂茄萣賜福宮和音社</p>
          </td>
          <td>
            <p>郭憲隆</p>
          </td>
          <td>
            <p>高雄市茄萣區賜福宮四館</p>
          </td>
          <td>
            <p>https://www.facebook.com/頂茄萣賜福宮和音社-941524995947236/</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>
            <p>每週三20:30-22:00練習</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>南海紫竹寺鴨母寮太平清歌陣</p>
          </td>
          <td>
            <p>林和順</p>
          </td>
          <td>
            <p>高雄市內門區光興里鴨母寮 12 號</p>
            <p>07-667-3713</p>
          </td>
          <td>
            <p>https://www.facebook.com/profile.php?id=100064261533397</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>
            <p>有活動才團練</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>蘇厝長興宮天子文生</p>
          </td>
          <td>
            <p>詹鈞現</p>
          </td>
          <td>
            <p>臺南市安定區蘇厝里 456 號</p>
            <p>06-592-2450</p>
          </td>
          <td>
            <p>https://www.facebook.com/a5922450</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>
            <p>2022年3月復陣，每週二19:30-21:30練習。7月開始由黃玉惠老師指導</p>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
