<template>
  <div>
    <div class="title">
      <h2>佛教音樂篇</h2>
    </div>
    <hr />
    <p class="firstRow"></p>

    <table rules="all" border="1" style="border: 1px solid" cellpadding="5">
      <thead>
        <tr>
          <th style="width: 20%">名稱</th>
          <th style="width: 20%">負責人</th>
          <th style="width: 25%">地址/電話</th>
          <th>其他聯絡方式</th>
          <th style="width: 25%">備註</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <p>海會寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>弘琳法師</p>
          </td>
          <td>
            <p>基隆市暖暖區八堵路1巷83號</p>
            <p>02-2457-2529</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>1951年由道源長老創建，1952年命名基隆正道山淨土宗海會寺。</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>靈泉禪寺</p>
          </td>
          <td>
            <p>方丈</p>
            <p>惟盛法師</p>
          </td>
          <td>
            <p>基隆市信義區六和街1號</p>
            <p>02-2465-3191</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/LingChuanNo1/">連結</a>
          </td>
          <td>
            <p>1900年創建，1903年命名靈泉寺。1907年善慧法師任住持，大力弘法興學。</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>中國佛教會</p>
          </td>
          <td>
            <p>理事長</p>
            <p>淨耀法師</p>
          </td>
          <td>
            <p>臺北市中正區紹興北街6號</p>
            <p>02-2321-9425</p>
          </td>
          <td>
            <a target="_" href="https://reurl.cc/X4KyWa/">連結</a>
          </td>
          <td>
            <p>1911年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>佛光山普門寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>滿方法師</p>
          </td>
          <td>
            <p>臺北市松山區民權東路三段136號</p>
            <p>02-2712-1177</p>
          </td>
          <td>
            <a target="_" href="http://pmt.fgs.org.tw/">連結</a>
          </td>
          <td>
            <p>1974年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>佛光山台北道場</p>
          </td>
          <td>
            <p>住持</p>
            <p>滿謙法師</p>
          </td>
          <td>
            <p>臺北市信義區松隆路327號6樓-14樓</p>
            <p>02-2762-0112</p>
          </td>
          <td>
            <a target="_" href="https://www.fgs.org.tw/tpevihara/">連結</a>
          </td>
          <td>
            <p>1994年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>善導寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>了中法師</p>
          </td>
          <td>
            <p>臺北市中正區忠孝東路一段23號</p>
            <p>02-2341-5758</p>
          </td>
          <td>
            <a target="_" href="https://www.shandaotemple.org.tw/">連結</a>
          </td>
          <td>
            <p>1929年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>法雨寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>定義法師</p>
          </td>
          <td>
            <p>臺北市北投區登山路108號</p>
            <p>02-2891-6762</p>
          </td>
          <td>
            <a target="_" href="https://reurl.cc/MbKV34">連結</a>
          </td>
          <td>
            <p>1905年創建，名大山寺，屬齋教道場。1947年妙湛法師住持道場，1949年更名法雨寺。</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>法鼓山農禪寺</p>
          </td>
          <td>
            <p>方丈</p>
            <p>果暉法師</p>
          </td>
          <td>
            <p>臺北市北投區大業路65巷89號</p>
            <p>02-2893-3161</p>
          </td>
          <td>
            <a target="_" href="https://ncm.ddm.org.tw/">連結</a>
          </td>
          <td>
            <p>1975年由東初老和尚創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>報恩寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>修謙法師</p>
          </td>
          <td>
            <p>臺北市士林區中山北路五段102號</p>
            <p>02-2881-2588</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>1922年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>地藏禪寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>地皎法師</p>
          </td>
          <td>
            <p>臺北市士林區延平北路七段189號</p>
            <p>02-2810-0237</p>
          </td>
          <td>
            <a target="_" href="https://globaldiza.blogspot.com/">連結</a>
          </td>
          <td>
            <p>1962年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>臨濟護國禪寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>悟潔法師</p>
          </td>
          <td>
            <p>臺北市中山區玉門街9號</p>
            <p>02-2594-8308</p>
          </td>
          <td>
            <a target="_" href="https://www.linchitemple.com/">連結</a>
          </td>
          <td>
            <p>
              臨濟護國禪寺為日本佛教臨濟宗鎮南山護國寺分院，創建於1900年。1912年舉行安座大典，是臺灣唯一以「護國」命名的佛寺。
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>十普寺</p>
          </td>
          <td>
            <p>方丈</p>
            <p>悟潔法師</p>
          </td>
          <td>
            <p>臺北市中正區南昌路二段140號</p>
            <p>02-2365-4734</p>
          </td>
          <td>
            <a target="_" href="https://reurl.cc/8Wx8bg">連結</a>
          </td>
          <td>
            <p>
              十普寺原名了覺寺，創建於1929年，1945年改為十普寺。1948年冬，白聖老法師駐錫後整建，乃成為中國式的叢林。
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>東和禪寺</p>
          </td>
          <td>
            <p>修慧法師</p>
          </td>
          <td>
            <p>臺北市中正區仁愛路一段21-33號</p>
            <p>02-2351-7887</p>
          </td>
          <td>
            <a target="_" href="http://www.dongher.org.tw/">連結</a>
          </td>
          <td>
            <p>1908年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>法鼓山</p>
          </td>
          <td>
            <p>方丈</p>
            <p>果暉法師</p>
          </td>
          <td>
            <p>新北市金山區法鼓路555號</p>
            <p>02-2498-7171</p>
          </td>
          <td>
            <a target="_" href="https://www.ddm.org.tw/">連結</a>
          </td>
          <td>
            <p>由聖嚴法師創立，2005年10月21日開山。</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>承天禪寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>道等法師</p>
          </td>
          <td>
            <p>新北市土城區承天路96號</p>
            <p>02-2267-1789</p>
          </td>
          <td>
            <a target="_" href="https://www.ctbm.org.tw/">連結</a>
          </td>
          <td>
            <p>1955年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>竹林禪寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>大寬法師</p>
          </td>
          <td>
            <p>新北市新店區文中路66號</p>
            <p>02-2911-1937</p>
          </td>
          <td>
            <a target="_" href="http://www.chulintemple.org/">連結</a>
          </td>
          <td>
            <p>1951年由天寧寺方丈證蓮大和尚，並其弟子戒德與佛聲2位法師創建。</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>西蓮淨苑</p>
          </td>
          <td>
            <p>住持</p>
            <p>惠敏法師</p>
          </td>
          <td>
            <p>新北市三峽區溪東路211巷31弄11號</p>
            <p>02-8676-1982</p>
          </td>
          <td>
            <a target="_" href="https://seelandboya.org/">連結</a>
          </td>
          <td>
            <p>1972年由智諭老和尚創立</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>金山寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>修熏法師</p>
          </td>
          <td>
            <p>新北市瑞芳區汽車路142號</p>
            <p>02-2497-2994</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>1930年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>南山放生寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>演觀法師</p>
          </td>
          <td>
            <p>新北市中和區忠孝街108號</p>
            <p>02-2945-0777</p>
          </td>
          <td>
            <a target="_" href="https://www.fangsheng.org.tw/">連結</a>
          </td>
          <td>
            <p>1961年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>靈巖山寺雙溪小築</p>
          </td>
          <td>
            <p>住持</p>
            <p>悟道法師</p>
          </td>
          <td>
            <p>新北市雙溪區大埤1-1號</p>
            <p>02-2493-0076</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/sxamtb/">連結</a>
          </td>
          <td>
            <p>2004年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>淨土院新北分院</p>
          </td>
          <td>
            <p>住持</p>
            <p>自誠法師</p>
          </td>
          <td>
            <p>新北市板橋區重慶路262號11樓</p>
            <p>02-2959-0209</p>
          </td>
          <td>
            <a target="_" href="http://plt1001.blogspot.com/">連結</a>
          </td>
          <td>
            <p>2012年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>寶纈禪寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>真璉法師</p>
          </td>
          <td>
            <p>新北市五股區成泰路四段43號</p>
            <p>02-2291-1632</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/BaoXieTemple/">連結</a>
          </td>
          <td>
            <p>1970年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>靈鷲山無生道場</p>
          </td>
          <td>
            <p>住持</p>
            <p>心道法師</p>
          </td>
          <td>
            <p>新北市貢寮區香蘭街7之1號</p>
            <p>02-2499-1100</p>
          </td>
          <td>
            <a target="_" href="https://www.093.org.tw/">連結</a>
          </td>
          <td>
            <p>1984年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>海明禪寺</p>
          </td>
          <td>
            <p>果印法師</p>
          </td>
          <td>
            <p>新北市樹林區海明街22號</p>
            <p>02-2681-2839</p>
          </td>
          <td>
            <a target="_" href="http://www.hmt.org.tw/abbot/">連結</a>
          </td>
          <td>
            <p>1960年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>香光山寺</p>
          </td>
          <td>
            <p>方丈</p>
            <p>悟因法師</p>
          </td>
          <td>
            <p>桃園市大溪區頭寮路276巷75-1號</p>
            <p>03-387-3141</p>
          </td>
          <td>
            <a target="_" href="https://gaya.gaya.org.tw/">連結</a>
          </td>
          <td>
            <p>2002年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>圓光禪寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>性尚法師</p>
          </td>
          <td>
            <p>桃園市中壢區聖德路一段888巷11號</p>
            <p>03-425-6168</p>
          </td>
          <td>
            <a target="_" href="https://www.ykcm.tw/">連結</a>
          </td>
          <td>
            <p>1907年創建，妙果老和尚1948年創辦臺灣佛學院。</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>法雲禪寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>達碧法師</p>
          </td>
          <td>
            <p>苗栗縣大湖鄉富興村11號</p>
            <p>03-799-1045</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>1914年由覺力法師創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>淨土院台中分院</p>
          </td>
          <td>
            <p>住持</p>
            <p>自誠法師</p>
          </td>
          <td>
            <p>臺中市西區五權西四街136號2樓</p>
            <p>04-2372-9239</p>
          </td>
          <td>
            <a target="_" href="http://plt1001.blogspot.com/">連結</a>
          </td>
          <td>
            <p>2012年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>南普陀寺</p>
          </td>
          <td>
            <p>方丈</p>
            <p>宗興法師</p>
          </td>
          <td>
            <p>臺中市北屯區松竹路一段8號</p>
            <p>04-2239-2816</p>
          </td>
          <td>
            <a target="_" href="https://www.youtube.com/channel/UClu0vTG1xjCWKLj-TaZb_5w">連結</a>
          </td>
          <td>
            <p>1957年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>慎齋堂</p>
          </td>
          <td>
            <p>林月嬌</p>
          </td>
          <td>
            <p>臺中市北屯區山西路二段272號</p>
            <p>04-2295-3293</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>1754年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>清雲寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>惟諦法師</p>
          </td>
          <td>
            <p>彰化縣彰化市中山路三段410巷13號</p>
            <p>04-732-3211</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>1971年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>中台禪寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>見燈法師</p>
          </td>
          <td>
            <p>南投縣埔里鎮中台路2號</p>
            <p>04-9293-0215</p>
          </td>
          <td>
            <a target="_" href="https://www.ctworld.org.tw/index.htm">連結</a>
          </td>
          <td>
            <p>2001年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>正覺精舍</p>
          </td>
          <td>
            <p>方丈</p>
            <p>果清律師</p>
          </td>
          <td>
            <p>南投縣埔里鎮獅子路1-6號</p>
            <p>04-9293-1907</p>
          </td>
          <td>
            <a target="_" href="http://www.lionccm.org/">連結</a>
          </td>
          <td>
            <p>1987年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>靈巖山寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>自興法師</p>
          </td>
          <td>
            <p>南投縣埔里鎮中正路105-1號</p>
            <p>04-9292-6336</p>
          </td>
          <td>
            <a target="_" href="http://www.taiwanlymt.org.tw/">連結</a>
          </td>
          <td>
            <p>1984年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>佛光山圓福寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>覺禹法師</p>
          </td>
          <td>
            <p>嘉義市東區圓福街37號</p>
            <p>05-277-2563</p>
          </td>
          <td>
            <a target="_" href="https://www.fgs.org.tw/branch/?BrID=D51101">連結</a>
          </td>
          <td>
            <p>1833年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>香光寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>明迦法師</p>
          </td>
          <td>
            <p>嘉義縣竹崎鄉內埔村溪州49之1號</p>
            <p>05-261-1010</p>
          </td>
          <td>
            <a target="_" href="http://www.gaya.org.tw/">連結</a>
          </td>
          <td>
            <p>1975年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>義德寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>紹安法師</p>
          </td>
          <td>
            <p>嘉義縣番路鄉內甕村凸湖5號</p>
            <p>05-259-1107</p>
          </td>
          <td>
            <a target="_" href="http://www.yidesi.org/">連結</a>
          </td>
          <td>
            <p>1911年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>彌陀禪寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>天露法師</p>
          </td>
          <td>
            <p>嘉義市彌陀路1號</p>
            <p>05-222-4203</p>
          </td>
          <td>
            <a target="_" href="http://fawang.ehosting.com.tw/mituo.htm">連結</a>
          </td>
          <td>
            <p>1752年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>大仙寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>傳證法師</p>
          </td>
          <td>
            <p>臺南市白河區岩前1號</p>
            <p>06-685-2143</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>1701年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>龍山禪院</p>
          </td>
          <td>
            <p>住持</p>
            <p>會寬法師</p>
          </td>
          <td>
            <p>臺南市歸仁區保大路一段152巷</p>
            <p>06-239-7197</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>1994年由會寬法師依循揚州高旻八角形禪堂而立，外方內圓。</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>法源禪寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>開雲法師</p>
          </td>
          <td>
            <p>臺南市學甲區新生路28號</p>
            <p>06-783-2401</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>1886年創建，初為齋教萬成堂。1948年惟覺禪師易名清涼山法源禪寺。</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>妙法禪寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>圓湛法師</p>
          </td>
          <td>
            <p>臺南市新營區復興路161巷42號</p>
            <p>06-656-2863</p>
          </td>
          <td>
            <a target="_" href="https://miaofatemple.weebly.com/">連結</a>
          </td>
          <td>
            <p>1935年建為佛堂名保安堂，1959年心揚法師重修，名妙法禪寺。</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>開元寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>郁定法師</p>
          </td>
          <td>
            <p>臺南市北區北園街89號</p>
            <p>06-237-5653</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>1690年創建，為臺灣最早之官方寺院。</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>打鼓岩元亨寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>淨明法師</p>
          </td>
          <td>
            <p>高雄市鼓山區元亨街7號</p>
            <p>07-521-3236</p>
          </td>
          <td>
            <a target="_" href="http://www.yht.org.tw/">連結</a>
          </td>
          <td>
            <p>
              1743年由經元法師創建，原名元興寺。1891年大火，後遷至現址改名元亨寺。1926年頌吉法師重建，額署「打鼓岩」。
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>超峰寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>天池法師</p>
          </td>
          <td>
            <p>高雄市阿蓮區崗山里5號</p>
            <p>07-633-2754</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>1665年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>圓照寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>敬定法師</p>
          </td>
          <td>
            <p>高雄市鳥松區坔埔路4巷10號</p>
            <p>07-731-9698</p>
          </td>
          <td>
            <a target="_" href="http://www.yct.com.tw/">連結</a>
          </td>
          <td>
            <p>1948年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>龍泉禪寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>和定法師</p>
          </td>
          <td>
            <p>高雄市鼓山區鼓山三路51巷59號</p>
            <p>07-521-7261</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>1744年由漳州高僧經元法師創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>佛光山</p>
          </td>
          <td>
            <p>住持</p>
            <p>心保法師</p>
          </td>
          <td>
            <p>高雄市大樹區興田路153號</p>
            <p>07-656-1921</p>
          </td>
          <td>
            <a target="_" href="https://www.fgs.org.tw/">連結</a>
          </td>
          <td>
            <p>1967年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>覺元寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>禪慧法師</p>
          </td>
          <td>
            <p>高雄市新興區仁愛一街11號</p>
            <p>07-215-9919</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>
              1953年創建，初奉關聖帝君，名覺善堂。1970年增建三寶殿，改為佛教道場，敦請菩妙老和尚為導師。
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>妙崇寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>宏安法師</p>
          </td>
          <td>
            <p>高雄市六龜區興龍里舊潭3-3號</p>
            <p>07-689-2259</p>
          </td>
          <td>
            <a target="_" href="http://www.clm.org.tw/">連結</a>
          </td>
          <td>
            <p>1964年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>宏法寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>圓塵法師</p>
          </td>
          <td>
            <p>高雄市新興區仁愛一街302號</p>
            <p>07-236-1189</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>1957年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>果碩大慈普利寺</p>
          </td>
          <td>
            <p>方丈</p>
            <p>堪千果碩仁波切</p>
          </td>
          <td>
            <p>屏東縣長治鄉長興村長安街59號</p>
            <p>08-736-6699</p>
          </td>
          <td>
            <a target="_" href="http://www.kunphen.com/">連結</a>
          </td>
          <td>
            <p>2017年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>明光寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>惟定法師</p>
          </td>
          <td>
            <p>宜蘭縣員山鄉湖北村大湖路95號</p>
            <p>03-922-3964</p>
          </td>
          <td>
            <a target="_" href="https://reurl.cc/Y9KpAL">連結</a>
          </td>
          <td>
            <p>1963年由紹悟法師創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>東林寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>法寂法師</p>
          </td>
          <td>
            <p>宜蘭縣冬山鄉太和村寶和路638號</p>
            <p>03-959-0000</p>
          </td>
          <td>
            <a target="_" href="http://www.donglin.tw/">連結</a>
          </td>
          <td>
            <p>1999年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>佛教慈濟慈善事業基金會</p>
          </td>
          <td>
            <p>住持</p>
            <p>證嚴法師</p>
          </td>
          <td>
            <p>花蓮縣新城鄉精舍街88巷1號</p>
            <p>03-826-6779</p>
          </td>
          <td>
            <a target="_" href="https://www.tzuchi.org.tw/">連結</a>
          </td>
          <td>
            <p>1966年創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>和南寺</p>
          </td>
          <td>
            <p>方丈</p>
            <p>道一法師</p>
          </td>
          <td>
            <p>花蓮縣壽豐鄉191號</p>
            <p>03-867-1001</p>
          </td>
          <td>
            <a target="_" href="http://www.indra-jala.com.tw/">連結</a>
          </td>
          <td>
            <p>1967年由傳慶老和尚創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>西泉寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>濬德法師</p>
          </td>
          <td>
            <p>澎湖縣湖西鄉91號</p>
            <p>06-992-2519</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>1959年由潔淨老和尚創建</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>妙雲講堂</p>
          </td>
          <td>
            <p>住持</p>
            <p>常光法師</p>
          </td>
          <td>
            <p>澎湖縣馬公市水源路2-1號</p>
            <p>06-926-7765</p>
          </td>
          <td>
            <a target="_" href="https://zh-tw.facebook.com/miaoyunphtw">連結</a>
          </td>
          <td>
            <p>1999年由嘉義妙雲蘭若住持慧理和常光法師所分設於澎湖的講堂</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>福慧寺</p>
          </td>
          <td>
            <p>住持</p>
            <p>見日法師</p>
          </td>
          <td>
            <p>金門縣金沙鎮光前里陽翟209號</p>
            <p>082-351-943</p>
          </td>
          <td>
            <a target="_" href="https://reurl.cc/Y9Kp2X">連結</a>
          </td>
          <td>
            <p>1999年由常實法師創建</p>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
